language: node_js
os:
  - osx

node_js: "0.12"

matrix:
  include:
    - os: linux
      env: TARGET_ARCH=arm
    - os: linux
      env: TARGET_ARCH=ia32
    - os: linux
      env: TARGET_ARCH=x64
  allow_failures:
    - os: osx

script: 'npm run test'

notifications:
  email: false
