os:
  - osx
  - linux
notifications:
  email: false
install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
  - nvm install stable
  - npm install -g npm
  - npm install
  - npm install coveralls istanbul
script:
  - npm run test
after_script:
  - ./node_modules/.bin/istanbul cover test.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
sudo: false
