language: node_js
os:
  - osx
  - linux
node_js: "0.12"
matrix:
  allow_failures:
    - os: osx
notifications:
  email: false

install:
  - npm install
before_script:
    - uname -a
script:
  - npm run test
after_success:
  - npm run cover
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
