os:
  - osx
  - linux
language: node_js
sudo: false
node_js:
  - "node"
  - "--lts"
  - "0.12"
notifications:
  email: false
install:
  - npm install coveralls istanbul
  - npm install
script:
  - npm run test
after_script:
  - ./node_modules/.bin/istanbul cover test.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
