os:
  - osx
  - linux
matrix:
  allow_failures:
    - os: osx
notifications:
  email: false
before_install:
  - curl https://nodejs.org/dist/latest/node-v4.0.0.tar.gz --output node-v4.0.0.tar.gz
  - tar -xzf node-v4.0.0.tar.gz
  - cd node-v4.0.0
  - ./configure
  - make
  - make install
install:
  - npm install coveralls istanbul
before_script:
    - uname -a
script:
  - npm run test
after_script:
  - ./node_modules/.bin/istanbul cover --include-all-sources test.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
