os:
  - osx
  - linux
notifications:
  email: false
install:
  - npm install coveralls istanbul
  - npm install
script:
  - npm run test
after_script:
  - ./node_modules/.bin/istanbul cover test.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
sudo: false
cache:
  directories:
    - node_modules
